#!/bin/bash

#test each script:
#raw2bin.py
#bin2hist.py -s 2048
#bin2bias.py -s 2048
#hist2pm3d.py
#C scripts as well!
#compare md5sums of good to bad

function checksum {
	CHECK=$(md5sum $1 | cut -b-32)
	GOOD=$(md5sum $1.good | cut -b-32)
	if [[ $CHECK = $GOOD ]]; then 
		echo "OK: $1"
	else
		echo "!!! BAD !!!: $1"
	fi
}

function status {
	echo -ne "$1...\033[0K\r"
}

if [[ $0 != "./test" ]]; then
	echo "Run me from my directory!"
	exit
fi

echo "Compiling C binaries..."
gcc ../raw2bin.c	-o ../raw2bin
gcc ../bin2bias.c	-o ../bin2bias

echo "Checking C binaries:"
status raw2bin
cat raw-test.good | ../raw2bin > sample-raw-test
checksum sample-raw-test
status vnf
cat sample-raw-test | ../vnf > sample-raw-test-vnf
checksum sample-raw-test-vnf
status bin2bias
cat sample-raw-test | ../bin2bias 2048 > sample-raw-test.bias
checksum sample-raw-test.bias

echo "Checking python scripts:"
status raw2bin.py
cat raw-test.good | ../raw2bin.py > sample-raw-test
checksum sample-raw-test
status vnf.py
cat sample-raw-test | ../vnf.py > sample-raw-test-vnf
checksum sample-raw-test-vnf
status bin2bias.py
cat sample-raw-test | ../bin2bias.py 2048 > sample-raw-test.bias
checksum sample-raw-test.bias
status bin2hist.py
cat sample-raw-test | ../bin2hist.py 2048 > sample-raw-test.hist
checksum sample-raw-test.hist
status hist2pm3d.py
cat sample-raw-test.hist | ../hist2pm3d.py > sample-raw-test.hist-cov
checksum sample-raw-test.hist-cov
